import mongoose from "mongoose";

const analysisSchema = new mongoose.Schema(
  {
    // ----------------------------------
    // User who performed the analysis
    // ----------------------------------

    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: [true, "User is required"],
      index: true,
    },

    // ----------------------------------
    // Resume information
    // ----------------------------------

    resume: {
      fileName: {
        type: String,
        required: [true, "Resume file name is required"],
        trim: true,
        maxlength: [255, "Resume file name is too long"],
      },

      fileType: {
        type: String,
        enum: [
          "application/pdf",
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        ],
        required: [true, "Resume file type is required"],
      },

      // Optional reference for future file storage
      storageKey: {
        type: String,
        trim: true,
        default: null,
      },
    },

    // ----------------------------------
    // Job Description
    // ----------------------------------

    jobDescription: {
      type: String,
      required: [true, "Job description is required"],
      trim: true,
      minlength: [20, "Job description is too short"],
      maxlength: [15000, "Job description is too long"],
    },

    // ----------------------------------
    // Analysis status
    // ----------------------------------

    status: {
      type: String,
      enum: ["completed", "failed"],
      default: "completed",
    },

    // ----------------------------------
    // Analysis Results
    // ----------------------------------

    matchScore: {
      type: Number,
      min: [0, "Match score cannot be less than 0"],
      max: [100, "Match score cannot be greater than 100"],
      required: function () {
        return this.status === "completed";
      },
    },

    // Skills found in both the resume and JD
    matchedSkills: {
      type: [String],
      default: [],
    },

    // Skills present in the JD but not sufficiently present
    // in the resume
    missingSkills: {
      type: [String],
      default: [],
    },

    // Scores for different analysis categories
    categoryScores: {
      type: Map,
      of: {
        type: Number,
        min: 0,
        max: 100,
      },
      default: {},
    },

    // Suggestions generated by the analysis system
    recommendations: {
      type: [String],
      default: [],
    },

    // ----------------------------------
    // Optional error information
    // ----------------------------------

    errorMessage: {
      type: String,
      default: null,
      trim: true,
      maxlength: [1000, "Error message is too long"],
    },
  },
  {
    timestamps: true,
  }
);

// ----------------------------------
// Index for user analysis history
// ----------------------------------

analysisSchema.index({
  user: 1,
  createdAt: -1,
});

const Analysis = mongoose.model("Analysis", analysisSchema);

export default Analysis;